---
- name: Baseline Docker (install and verify)
  hosts: all
  gather_facts: false
  become: true
  pre_tasks:
    - name: Skip baseline when running in simulate mode
      meta: end_play
      when: simulate | default(false)

    - name: Wait for SSH availability
      wait_for_connection:
        timeout: "{{ ssh_wait_timeout | default(60) }}"
        sleep: 5
        connect_timeout: 5

    - name: Wait for cloud-init completion if present
      command: test -f /var/lib/cloud/instance/boot-finished
      register: cloud_init_ready
      retries: 12
      delay: 5
      until: cloud_init_ready.rc == 0
      changed_when: false
      failed_when: false

  tasks:
    - name: OPERATION_STEP docker:install start
      shell: |
        printf 'OPERATION_STEP={"name":"docker:install","status":"running"}\n'
      args:
        executable: /bin/sh

    - name: Install Docker packages (docker.io)
      apt:
        name:
          - docker.io
        state: present
        update_cache: true

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Verify Docker daemon is responsive
      command: docker info
      register: docker_info_result
      failed_when: docker_info_result.rc != 0

    - name: OPERATION_STEP docker:install completed
      shell: |
        printf 'OPERATION_STEP={"name":"docker:install","status":"completed"}\n'
      args:
        executable: /bin/sh

    - name: OPERATION_STEP baseline:complete
      shell: |
        printf 'OPERATION_STEP={"name":"baseline:complete","status":"completed"}\n'
      args:
        executable: /bin/sh
